# Generated by Django 5.1.5 on 2025-01-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_user_alter_rate_user'),
        ('user', '0004_remove_user_email_remove_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
