# Generated by Django 5.1.5 on 2025-01-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('user', '0004_remove_user_email_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Content',
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='Rate',
        ),
    ]
