# Generated by Django 5.1.5 on 2025-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='total_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rate',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
